reduce the look in the cdr

diff --git a/kubectl-grab_resources b/kubectl-grab_resources
--- a/kubectl-grab_resources
+++ b/kubectl-grab_resources
@@ -83,24 +83,18 @@ function collect_resources {
 
 function collect_customresroucedefition {
     # pack some of the CustomResourceDefinition implemented
-    cdr_names=$(kubectl get customresourcedefinition -A --no-headers -o custom-columns=":metadata.name")
+    cdr_names=$(kubectl get customresourcedefinition -A --no-headers --selector="$1" -o custom-columns=":metadata.name")
 
     # shellcheck disable=SC2116
     for cdr_name in $(echo "${cdr_names}")
     do
-        # shellcheck disable=SC1083
-        crd_child=$(kubectl get customresourcedefinitions -A --no-headers --selector="$1" -o custom-columns=":metadata.name")
-    
-        for name in $(echo "${crd_child}")
-        do
-            echo "---" >> "${OUTPUT_YAML}"
-            kubectl get customresourcedefinitions "${name}" -o yaml | kubectl neat >> "${OUTPUT_YAML}"
-            if [[ $? != 0 ]]; then
-                echo "cannot execute kubectl command.."
-                exit 1
-            fi
-            echo "Packed ${name} from ${cdr_name} namespace: ${namespace}"
-        done
+        echo "---" >> "${OUTPUT_YAML}"
+        kubectl get customresourcedefinitions "${cdr_name}" -o yaml | kubectl neat >> "${OUTPUT_YAML}"
+        if [[ $? != 0 ]]; then
+            echo "cannot execute kubectl command.."
+            exit 1
+        fi
+        echo "Packed ${name} from customresourcedefinitions..."
    done
 }
 
